// Auto-generated by scripts/generate-manifest.mjs
            var manifest = {
                bundles: [
  {
    name: "common",
    assets: [
      {
        alias: "bg",
        src: "./assets/common/bg.png",
        type: "image"
      }
    ]
  },
  {
    name: "loadingScene",
    assets: [
      {
        alias: "loading_bg",
        src: "./assets/loadingScene/loading_bg.jpg",
        type: "image"
      },
      {
        alias: "loading_fill",
        src: "./assets/loadingScene/loading_fill.png",
        type: "image"
      }
    ]
  },
  {
    name: "startScene",
    assets: [
      {
        alias: "start_bg",
        src: "./assets/startScene/start_bg.jpg",
        type: "image"
      }
    ]
  }
]
                };
            export default manifest;
        