// Auto-generated by scripts/generate-manifest.mjs
            var manifest = {
                bundles: [
  {
    name: "common",
    assets: [
      {
        alias: "bg",
        src: "./assets/common/bg.png",
        type: "image"
      }
    ]
  }
]
                };
            export default manifest;
        